
model_name: "resnet18"
dataset: "cifar"

total: 4
selected: 3
global_epochs: 20
local_epochs: 3

batch_size: 32
lr: 0.1
momentum: 0.9
lambda: 0.1
eta: 0.1

# 使用迪利克雷分布模拟 non-iid
using_dirichlet: True
dirichlet_alpha: None