
model_name: "resnet18"
dataset: "cifar"

total: 4
selected: 3
global_epochs: 100
local_epochs: 2

batch_size: 64
test_batch_size: 64
lr: 0.01
momentum: 0.0001
lambda: 0.1

# 使用迪利克雷分布模拟 non-iid
using_dirichlet: True
dirichlet_alpha: None

adversary_num: 1
poison_images_test:
  - 330
  - 568
  - 3934
  - 12336
  - 30560
poison_images:
  - 30696
  - 33105
  - 33615
  - 33907
  - 36848
  - 40713
  - 41706
size_of_secret_dataset: 200